version: 0.0

os: linux

files:
  - source: s3://codepipeline-us-east-1-591546837593/receeve-mailgun-conn/BuildArtif/
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root

permissions:
  - object: /var/www/html
    pattern: "**"
    owner: root
    group: root
    mode: 755