version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing the project...
      - npm install
  build:
    commands:
      - echo Building the project...
      - npx sls package --package build
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp build/createLambdaMailgunData.zip s3://codepipeline-us-east-1-591546837593/receeve-mailgun-conn/BuildArtif/createLambdaMailgunData-$(date +%s).zip

artifacts:
  type: none
