version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email)
  build:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Build started on `date`
      - npm ci
      - npx sls package
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  type: zip
  files:
    - package.zip
