version: 0.2

phases:
  build:
    commands:
      - echo Building the project...
      - npm ci
      - sls package --package build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/createLambdaMailgunData.zip
