version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing the project...
      - npm install
  build:
    commands:
      - echo Building the project...
      - npx sls package --package build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - 'build/*'
    - 'appspec.yml'
    - 'before_install.sh'
    - 'after_install.sh'
  target-path: 's3://codepipeline-us-east-1-591546837593/receeve-mailgun-conn/BuildArtif/'