version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing the project...
      - npm install
  build:
    commands:
      - echo Building the project...
      - serverless package --package build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/createLambdaMailgunData.zip
