version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g serverless
      - npm install
      - sls plugin install -n serverless-offline
      - sls plugin install -n serverless-dynamodb-local
      - sls plugin install -n serverless-esbuild
      - sls dynamodb install