version: 0.2

phases:
  install:
    commands:
      - nvm install v14.18.0
      - nvm use v14.18.0
      - npm install -g serverless
      - npm install
      - sls plugin install -n serverless-offline
      - sls plugin install -n serverless-dynamodb-local
      - sls plugin install -n serverless-esbuild
      - sls dynamodb install
  build:
    commands:
      - npx sls esbuild
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying the Lambda function...
      - npx sls deploy